baseURL = "https://hanivan.github.io/lintascatatan/"
languageCode = "en-us"
title = "Lintas Coretan Milenial"
theme = "ltheme"
summaryLength = 25
paginate = 2

[params]
	Description = "Tempat dimana yang nantinya akan disebut sebuah buku online"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
